openapi: 3.0.0
info:
  title: Mandalorian API
  description: API to set and recover images from a camera
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: images
    description: Set of endpoints for setting and retrieving images from a camera.
paths:
  /images:
    get:
      tags:
        - images
      summary: Returns a list of images.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: idCamera
          in: query
          required: true
          description: ID of the camera that you want to consult
          schema:
            type : string
            example: "CAM001"
      responses:
        '200':    # status code
          description: Id of the camera with its current image
          content:
            application/json:
              schema:
                type: object
                properties: 
                  idCamera: 
                    type: string
                    description: Id of the camera
                    example: "CAM001"
                  image:
                    type: string
                    format: byte 
                    description: Image of the camera in base64 format
                    example: "U3dhZ2dlciByb2Nrcw=="

    post:
      tags:
        - images
      summary: Post an image to a camera.
      description: Post an image to the given camera
      parameters:
        - name: idCamera
          in: path
          required: true
          description: ID of the camera that you want to consult
          schema:
            type : string
            example: "CAM001"
      requestBody:
        required: true
        content:
           image/*:    # Can be image/png, image/svg, image/gif, etc.
            schema:
              type: string
              format: binary

      responses:
        '204':    # status code
          description: No content
        