openapi: 3.0.0
info:
  title: Mandalorian API
  description: API to set and recover images from a camera
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Optional server description, e.g. Main (production) server 
tags:
  - name: images
    description: Set of endpoints for setting and retrieving images from a camera.
paths:
  /images:
    get:
      tags:
        - images
      summary: Returns a list of images.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: idCamera
          in: query
          required: true
          description: ID of the camera that you want to consult
          schema:
            type : string
            example: "CAM001"
      responses:
        '200':    # status code
          description: Id of the camera with its current image
          content:
            image/png:
              schema:
                type: string
                format: binary 
                    
  /images/{idCamera}:
    post:
      tags:
        - images
      summary: Post an image to a camera.
      description: Post an image to the given camera
      parameters:
        - name: idCamera
          in: path
          required: true
          description: ID of the camera that you want to consult
          schema:
            type : string
            example: "CAM001"
      requestBody:
        required: true
        content:
            multipart/form-data:    # Can be image/png, image/svg, image/gif, etc.
              schema:
                type: object
                properties:
                  file:
                    type: string
                    format: binary

      responses:
        '204':    # status code
          description: No content
        